'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Tasks', [
      {task_name: 'Anode Rod Replacement', checked: false, description: 'Inspect Anode Rod in Water Heater', imageLink: 'http://www.azhomewater.com/images/product-amoderod.png', timeFrame: 'annually', category: 'plumbing', skillLevel: 'beginner', internetSearch: 'anode rode inspection', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Drain Water Heater', checked: false, description: 'Drain water heater to prevent sediment', imageLink: 'http://images.trulia.com/blogimg/6/5/8/7/1066338_1305628021732_o.jpg', timeFrame: 'annually', category: 'plumbing', skillLevel: 'beginner', internetSearch:   'how to drain water heater', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Turn off/on water supply valves under sinks and toilets', checked: false, description: 'Turn off/on water supply valves under sinks and toilets to prevent them from sticking.', imageLink: 'https://cdn1.tmbi.com/TFH/Step-By-Step/FH03MAY_SINKVA_03.JPG', timeFrame: 'annually', category: 'plumbing', skillLevel: 'beginner', internetSearch: 'how to turn off sink valves' , createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Pour Water Into Drains', checked: false, description: 'Pour a gallon of water into drains that are not used often including floor drains to fill the trap and prevent odors', imageLink: 'https://www.sparkleteam.com/wp-content/uploads/2013/04/pouring-chemicals-down-a-drain-225x300.jpg', timeFrame: 'annually', category: 'plumbing', skillLevel: 'beginner', internetSearch: 'how to eliminate drain odors', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Inspect Filters Throughout Home', checked: false, description: 'Inspect filters and cartridges throughout the home including furnace, fridge, water purifier; replace as needed.', imageLink: 'http://g-ecx.images-amazon.com/images/G/01/th/aplus/ge_mwf_filter_fridge2._V167585617_.jpg', timeFrame: 'monthly', category: 'general home maintenence', skillLevel: 'beginner', internetSearch:   'replace furnace or fridge filter' , createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Furnace Tune-up and Cleaning', checked: false, description: 'Have a professional come out and perform a tune-up and cleaning', imageLink: 'http://www.mm-plumbing.com/wp-content/uploads/2014/04/tune-up-furnace.jpg', timeFrame: 'fall', category: 'HVAC', skillLevel: 'professional', internetSearch:   'furnace tune-up special' , createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Air Conditioner or Swamp Cooler Tune-up and Cleaning', checked: false, description: 'Have a professional come out and perform a tune-up and cleaning', imageLink: 'http://www.planoairconditioningandheating.com/ac-repair/plano-air-conditioning-tune-up-list.jpg', timeFrame: 'spring', category: 'HVAC', skillLevel: 'professional', internetSearch:   'air conditioner tune-up special', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Check Vents', checked: false, description: 'Check all vents in home to make sure they are open', imageLink: 'https://www.revlocal.com/FileStore.ashx?id=95706', timeFrame: 'fall', category: 'HVAC', skillLevel: 'beginner', internetSearch:   'how to open vents in home', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Inspect Window and Door Seals', checked: false, description: 'Inspect Window and Door Seals replace or fix as needed', imageLink: 'https://www.todayshomeowner.com/screengrabs/639-10-how-replace-worn-weatherstripping-doors.jpg', timeFrame: 'fall', category: 'general home maintenance', skillLevel: 'beginner', internetSearch:   'DIY replace weatherstripping', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Inspect Dryer Vents and Vent Hose', checked: false, description: 'Inspect Dryer vents and vent hose for blockage.  Clean as needed.', imageLink: 'http://www.kaypratt.com/blog/wp-content/uploads/2013/05/cloggeddryervent.jpg', timeFrame: 'annually', category: 'general home maintenance', skillLevel: 'beginner', internetSearch:   'how to clean dryer vent and hose', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Check Flue or Chimney', checked: false, description: 'Visually look over the flue or chimney for any cracks holes or corrosion. Some small flue leaks can be seals with foil tape. Chimney repairs must be done by a professional mason.', imageLink: 'http://www.certifiedcraftsmen.com/content/images/chimney/classa_b.jpg', timeFrame: 'annually', category: 'HVAC', skillLevel: 'beginner', internetSearch:   'How to check the flue on the roof', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Fertilize Lawn', checked: false, description: 'Fertilize your lawn at least four times per year. Ask home and garden center for type of fertilizer for your area.', imageLink: 'http://hoosierhomemade.com/wp-content/uploads/lawn-fertilizing-dos-donts-post.jpg', timeFrame: 'all seasons', category: 'landscaping', skillLevel: 'beginner', internetSearch:   'how to fertilize a lawn', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Clean Raingutters', checked: false, description: 'Clean out raingutters to prevent downspout blockage', imageLink: 'http://seminolepowerwash.com/wp-content/uploads/2014/05/Gutter-Cleaning1.jpg', timeFrame: 'all seasons', category: 'landscaping', skillLevel: 'beginner', internetSearch:   'how to clean out raingutters', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Winterize Sprinkler System', checked: false, description: 'Turn off sprinkler system open valves blow-out lines', imageLink: 'https://images.plantcaretoday.com/wp-content/uploads/winterinze-sprinkler-09302016-1200x630.jpg', timeFrame: 'fall', category: 'landscaping', skillLevel: 'beginner', internetSearch: 'how to drain sprinkler system', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Check Outdoor Hosebibbs for Leaks', checked: false, description: 'Check oudoor hosebibbs for leaks disconnect all hoses to prevent freezing.', imageLink: 'https://i.pinimg.com/736x/de/30/78/de3078de16b5c7473664287cd447300b.jpg', timeFrame: 'fall', category: 'landscaping', skillLevel: 'beginner', internetSearch: 'how to check hosebibb', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Change batteriesin smoke detetctors', checked: false, description: 'Change batteries in all smoke and carbon monoxide detectors', imageLink: 'https://unitedelectricalgroup.net.au/wp-content/uploads/2017/02/Chirping-Smoke-Alarm-Battery-Cover.jpg', timeFrame: 'fall', category: 'general home maintenance', skillLevel: 'beginner', internetSearch:   'how to change batteries in smoke detectors', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Inspect exterior paint and touch up', checked: false, description: 'Inspect exterior paint on siding, window frames, etc., and check for missing paint or damage.  Touch up yourself or hire a professional.', imageLink: 'http://successpatheducation.com/wp-content/uploads/sites/8/2016/05/exterior-paint-is-a-touch-up-enough.jpg', timeFrame: 'spring', category: 'painting', skillLevel: 'beginner', internetSearch: 'inspect for paint chips', createdAt: new Date(), updatedAt: new Date()}, 
      {task_name: 'Inspect Roof Shingles', checked: false, description: 'Inspect the shingles on your roof check for cracks, peeling, curling or missing shingles. Replace as necessary.', imageLink: 'https://i.pinimg.com/736x/36/ec/ab/36ecabfed4fbbbd88650b0ec762147db.jpg', timeFrame: 'fall', category: 'roofing', skillLevel: 'beginner', internetSearch: 'how to replace individual shingles on a roof' , createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Prune shrubs after they bloom', checked: false, description: 'Prune shrubs after they bloom, always making sure to remove any decayed or dead branches. Each shrub may require pruning at different times.', imageLink: 'http://img2-1.timeinc.net/toh/i/g/11/yard/03-shrub-pruning/04-dos-and-donts.jpg', timeFrame: 'spring', category: 'landscaping', skillLevel: 'beginning', internetSearch:   'how to prune bushes', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Inspect Outdoor Play Equipment', checked: false, description: 'Inspect outdoor play equipment for cracks, loose bolts, rusty chains, split or cracked wood.  Perform repairs or hire professional.', imageLink: 'https://i.pinimg.com/736x/9a/67/5d/9a675dbd0eb0d370feea5272ca477356.jpg', timeFrame: 'spring', category: 'landscaping', skillLevel: 'beginner', internetSearch:   'how to repair outdoor play equipment', createdAt: new Date(), updatedAt:  new Date()}, 
      {task_name: 'Vacuum Refrigerator Coils', checked: false, description: 'Remove the coil cover and vacuum the dust off of the refrigerator coils', imageLink: 'https://www.onegoodthingbyjillee.com/wp-content/uploads/2012/06/cleaning-refrigerator-coils-8.jpg', timeFrame: 'all seasons', category: 'general home maintenance', skillLevel: 'beginner', internetSearch: 'how to clean fridge coils', createdAt: new Date(), updatedAt:  new Date()}
      ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Tasks', null, {truncate : true});
	}
};
